CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(150) NOT NULL,
  published_year INT,
  is_public BOOLEAN NOT NULL DEFAULT TRUE
);

-- Ako tablica već postoji od ranije bez ove kolone, dodaj je
ALTER TABLE books ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT TRUE;
